server:
  port: 8080
spring:
  application:
    name: ApiGateway

  cloud:
    gateway:
      routes:
        - id: taskService
          uri: http://localhost:8082/
          predicates:
            - Path=/tasks/**

#        - id: eureka-server
#          uri: http://localhost:8761/
#          predicates:
#            - Path=/eureka-server/**